language: python
python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
script: nosetests
env:
  global:
  - secure: gaJAME9M4oSiZHDzIT0gEM56ZVMd4phXmDk/2h9rWAqPsd6cZAiE3OZtyfJWUsc9yCk51CaGJjz7QQjL02+Qq10r6GhczhzzwyxhbW7eN1Nc8gEOIHw8rJXIEmcH5kyCdNisGFKGkzgaQxXUFqC+eUXZoxfNBEQGNcSYmMszY8M=
  - secure: C+RXnP2xkQFIPRKcDhEV0IfFoZi9Y59r9vuHUOMZ5oZVzZUQouGGY368Tca1JNZxj2n7EdjIEE+JI5WgCGgtWMu804Jn4EzIof7/DAALtifioqDlEx63Cd0z0u0qzc799nOOrh/c5+fO1CinJOo5+86M2CpawS8RykF3kbeRlNU=
  - secure: B3O++9TIXjEacCoNyqtz0B5pC6PBmDJ5Jyvope+beDaYcrWwg6Rs4QJR6UQz2F8/gLUToEeKboepANcNRUuitEP2lcCanzxL6vRheLovKZpEIVT9QipZKZ067lc5FgCO3svIyf0fXv30xQnpXwB8zKZNmlh6OecpkfHVdshmrgs=
  - secure: XuQG41Las1yJ7RX5OBY975bc3m742y7gUvxxZfs8Dxj9s+N7b3K7nfGyOedrNNSyRdgkxkZ1f1/y+NP9JOySU7rgl6CVR417W/KkT6aDLxpgieV+ooQdD2uzVJ5Mr2u9kP+SuFAR4ONAi7Uy9e5t8c8RfsqJagDu8zK9h6+/8s4=
  - secure: XaznMBcx2P1OkDfLj0I9Ee9tZMYPyg+9HS4uSJWTCfavG4uRLDPajWhvyK8bIy3rU8JAuTuukc7s9pbFgLxsdQUf8iQqEqUWi01+jKpyHo9hymD7ygZHWpAQP/sUZ6FjAjvCurEHN/1SH0jWkp/DdWzj+SiYhPIUjYNLIgStNeQ=
  - secure: iMNMPbGKCCsiFrtP8gU5YLh8euTZyXCoqXDlaFOI8GfqJQ7y3YuZIhfu6O7eXxWwxJFQWsig3uNTE/3EG0I/OF4zN1O6RdGVMO0sHKs6gmPvVgHKRBtCe1NSKrxXjlm1K5GpDICFgf2VL6kRn/hB+OkfpLAo5Mq7U86JXF4QR+A=
